import{a as b,S as L,i as a}from"./assets/vendor-C4-ZuMk8.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const q="47111557-92c37ade8bb97610ca7074a51",v="https://pixabay.com/api/";async function g(r,e){return(await b.get(v,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}const w=new L(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function p(r){const e=document.querySelector(".gallery"),o=r.map(s=>`
    <div class="gallery-item">
      <a href="${s.largeImageURL}" data-caption="${s.tags}">
        <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" class="gallery-image" />
      </a>
      <div class="image-info">
        <p><strong>Likes:</strong> ${s.likes}</p>
        <p><strong>Views:</strong> ${s.views}</p>
        <p><strong>Comments:</strong> ${s.comments}</p>
        <p><strong>Downloads:</strong> ${s.downloads}</p>
      </div>
    </div>
  `).join("");e.innerHTML+=o,w.refresh()}function S(){const r=document.querySelector(".gallery");r.innerHTML=""}const u=document.querySelector(".search-form"),m=document.querySelector(".loader-container"),f=document.querySelector(".loader"),i=document.querySelector(".load-more");let l="",c=1;u.addEventListener("submit",async r=>{if(r.preventDefault(),l=u.elements.query.value.trim(),!l){a.error({title:"Error",message:"Please enter a search query"});return}S(),c=1,h(),i.style.display="none";try{const e=await g(l,c);y();const o=e.hits;if(console.log(o),Array.isArray(o)&&o.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}Array.isArray(o)?(p(o),i.style.display="block"):console.error("Expected an array but got:",o)}catch(e){y(),a.error({title:"Error",message:e.message})}});i.addEventListener("click",async()=>{c+=1,h();try{const r=await g(l,c);y();const e=r.hits;if(console.log(e),Array.isArray(e)&&e.length===0){a.error({title:"Error",message:"We're sorry, but you've reached the end of search results."}),i.style.display="none";return}Array.isArray(e)?(p(e),E()):console.error("Expected an array but got:",e)}catch(r){y(),a.error({title:"Error",message:r.message})}});function h(){f.style.display="block",m.style.display="flex"}function y(){f.style.display="none",m.style.display="none"}function E(){const r=document.querySelector(".gallery-item");if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}else console.error("Gallery item not found")}
//# sourceMappingURL=index.js.map
