import{a as L,S as v,i as n}from"./assets/vendor-C4-ZuMk8.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const u of a.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(t){if(t.ep)return;t.ep=!0;const a=o(t);fetch(t.href,a)}})();const q="47111557-92c37ade8bb97610ca7074a51",w="https://pixabay.com/api/";async function p(r,e){return(await L.get(w,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}const S=new v(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function f(r){const e=document.querySelector(".gallery"),o=r.map(s=>`
    <div class="gallery-item">
      <a href="${s.largeImageURL}" data-caption="${s.tags}">
        <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" class="gallery-image" />
      </a>
      <div class="image-info">
        <p><strong>Likes:</strong> ${s.likes}</p>
        <p><strong>Views:</strong> ${s.views}</p>
        <p><strong>Comments:</strong> ${s.comments}</p>
        <p><strong>Downloads:</strong> ${s.downloads}</p>
      </div>
    </div>
  `).join("");e.innerHTML+=o,S.refresh()}function E(){const r=document.querySelector(".gallery");r.innerHTML=""}const g=document.querySelector(".search-form"),m=document.querySelector(".loader-container"),h=document.querySelector(".loader"),l=document.querySelector(".load-more");let c="",i=1,y=0;g.addEventListener("submit",async r=>{if(r.preventDefault(),c=g.elements.query.value.trim(),!c){n.error({title:"Error",message:"Please enter a search query"});return}E(),i=1,y=0,b(),l.style.display="none";try{const e=await p(c,i);d();const o=e.hits;if(y=e.totalHits,console.log(o),Array.isArray(o)&&o.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}Array.isArray(o)?(f(o),y>15&&(l.style.display="block")):console.error("Expected an array but got:",o)}catch(e){d(),n.error({title:"Error",message:e.message})}});l.addEventListener("click",async()=>{i+=1,b();try{const r=await p(c,i);d();const e=r.hits;if(console.log(e),Array.isArray(e)&&e.length===0){n.error({title:"Error",message:"We're sorry, but you've reached the end of search results."}),l.style.display="none";return}Array.isArray(e)?(f(e),A(),i*15>=y&&(l.style.display="none",n.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))):console.error("Expected an array but got:",e)}catch(r){d(),n.error({title:"Error",message:r.message})}});function b(){h.style.display="block",m.style.display="flex"}function d(){h.style.display="none",m.style.display="none"}function A(){const r=document.querySelector(".gallery-item");if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}else console.error("Gallery item not found")}
//# sourceMappingURL=index.js.map
